language: python
python:
  - "3.6"

sudo: false

before_install:
  - python --version
  - uname -a
  - lsb_release -a

install:
  - pip install coverage
  - pip install coveralls
  - pip install -r requirements.txt
  - pip --version
  - export PYTHONPATH=${PYTHONPATH}:${TRAVIS_BUILD_DIR}/src

before_script:

script:
  - echo $(PYTHONPATH)
  - echo $(pwd)
  - pytest

notifications:
  email:
    on_success: never
    on_failure: always
